### ISSUE TITLE
Configure security updates in chef recipes

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#382]
We need our cloud servers to be applying security updates, really, otherwise we're going to get caught out.

**Comment by Floppy** [comment]
@pikesley is this being done automatically in the new cookware? Can this be closed, or should we bring it in and make the change now?

**Comment by pikesley** [comment]
I have a better idea here, I think. This is a bit hand-wavy, but:

* Can we set an alert that tells us when any of our instances are more than (say) 2 weeks old, so we can recycle them?

Everything should be Identical, Repeatable and Disposable. We're moving more and more of our databases &c to Thing-as-a-Service, so that's fine. We'd want to move to using the Rackspace API for provisioning load-balancers, but we should be doing that anyway, really.

Maybe [Otto](https://ottoproject.io/) can help here.

This will give us high-latency Continuous Integration as a bonus side-effect.

Opinions?

**Comment by tonymarklove** [comment]
Forgive my lack of background knowledge but is there a reason we're not deployed on Heroku or similar. Let someone else handle all the headaches?

**Comment by pezholio** [comment]
Heroku is great (and we use it for a lot of small projects), but I think the reason we don't use it for bigger projects is that at scale it's super expensive.

As for the idea - I'm bang up for that. Servers as cattle, not pets and all that. Also, high-latency CI with Otto would be amazing.
