### ISSUE TITLE
Setup automated, 'unmanned' distillation

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#487]
Setup anything is necessary to distill the OA dataset automatically periodically, e.g. every night.

**Comment by pezholio** [comment]
OK, so this can be done pretty easily I think. Here's what I think we need to do:

- [ ] Adjust Ernest to allow 'last updated since' searches (as per https://github.com/OpenAddressesUK/ernest/issues/20)
- [ ] Tweak distiller to make the 'last updated since' requests to Ernest
- [ ] Set up distiller to run on a daily basis using Heroku scheduler

One thing we will need to work around is Heroku's limit on the amount of time jobs can run for, which we encountered when doing the inital distil. We may need to move distiller away from Heroku and onto AWS in the medium term.

**Comment by pezholio** [comment]
I've done all this, and made the changes in the app on Heroku. Distil will now run every day at 2:00 UTC. It won't (yet) do anything, as we don't have any addresses added to Ernest, but the pipework is laid...

**Comment by giacecco** [comment]
@pezholio does the scheduler manage the scenario in which a previous distillation is not complete before the new one is launched?

**Comment by pezholio** [comment]
Yeah, it basically asks Ernest for any addresses which have been distilled since the date the last address was added, so yes, it'll cover that
