### ISSUE TITLE
OA Website: mobile templates improvements

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#515]
@peterkwells please specify here your requirements.

**Comment by peterkwells** [comment]
1. As per numerous pieces of feedback the website needs to be responsive and accessible on mobile devices
2. At least one piece of feedback has reported overlapping text on mobile. 

Iterate, rather than specify a desired end-goal, and make incremental improvements. Either Emma or Peter can do simple validation with the dev.

**Comment by giacecco** [comment]
For the UX person

**Comment by giacecco** [comment]
Removed from Tech Team's planning as this is being taken care of by Error.
