### ISSUE TITLE
ODI website: job ad page not working properly

### ISSUE THREAD

**Issue by sumikasan** [theodi/shared#533]
We seem to be having issues with a new job generating on the /jobs page. 
I’ve taken a look at Panopticon and Publisher and can’t seem to see anything that has gone awry. 
There are currently a job that is live but not generating.

**Comment by pezholio** [comment]
This is all down to caching. I've fixed the immediate issue (and one that Steff was having with courses), but the underlying issue is a mystery. I've removed all mention of caching from the content api config in the hope that this will go away, but I'm not confident. 

I'm going to close this for now, but I've asked people to be vigilant in case this issue happens again.
