### ISSUE TITLE
Rebrand Turbot

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#534]

**Comment by pikesley** [comment]
turbot_server/app/views/docs/_intro.html.erb as a starting point

**Comment by giacecco** [comment]
@pezholio suggested it is faster if he does the job and I just provide text or images. If @floppy was already planning to write/revise Turbot's documentation, he may take this task too.

Here are the quick and dirty changes for the weekend. 

- [ ] replace header logo with https://dl.dropboxusercontent.com/u/13837050/turbot-temp/header-logo.png ; I prepared the new images so that they are identical in size to the original and nothing should break; clicking of course should go to https://openaddressesuk.org
- [ ] replace welcome text "Welcome to Turbot! This is where OpenCorporates..." with "Welcome to Turbot! This is where [Open Addresses](https://openaddressesuk.org)' hosts its own and our contributors' ETLs and inference engines".
- [ ] remove "Developers can host their own corporate data scrapers here, and help increase the amount of open corporate data in the world."
- [ ] there are references to "OpenCorporates" and "corporate data" everywhere. Just search for "OpenCorporates" and "corporate" and adapt the text at every occurrence with "Open Addresses" and "address data" or delete what is not applicable
- [ ] add something like the following statement at the beginning of the "Credits" section: "Turbot was originally conceived by the great team at [OpenCorporates](https://openaddressesuk.org). It's our ambition is, one day, to converge the effort we put into our forking our own version of Turbot back in OpenCorporates' master."
- [ ] change the "Support / Contact us" section to:

```
We can't achieve our goal without your help.

If you've got any ideas on how to improve the website, or you're stuck on something, or you've found a bug, please get in touch using one of these methods:

- [Our forum](https://github.com/OpenAddressesUK/forum/issues) is our preferred route, because we're a small team and aren't always online. It allows any of us to respond, and also build up an archive of knowledge.
- If it's a general question about open data, copyright, approaches to scraping etc, then [OpenData StackExchange](http://opendata.stackexchange.com/) is a good choice, as it helps build up common knowledge about open data.
- You can always email us at info@openaddressesuk.org.
```

**Comment by Floppy** [comment]
OK, I'm going to start this all now.

**Comment by Floppy** [comment]
Done. I'll make more changes in the docs as I go.
