### ISSUE TITLE
Move maps on the website from OSM to OS Street View

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#536]

**Comment by Floppy** [comment]
Done in https://github.com/OpenAddressesUK/theodolite/pull/112 - ready to merge.

**Comment by Floppy** [comment]
Works lovely. https://alpha.openaddressesuk.org/addresses/FSjJCH.

I've not tweaked the attribution statement, just used what was in their example. @peterkwells @giacecco want to check you're OK with it?

**Comment by peterkwells** [comment]
Looking at attrib now

**Comment by peterkwells** [comment]
Worked through Ts/Cs/site/etc. Some key points below. Doesn't quite work at the mo..., 3 and 4 are the key bits.

1. To clarify the q yesterday. No. we cannot serve the OS data (see 1) or make money from it (see 7). Those are both fine.
2. We should be careful of derived data (see 3). As it stands it's fine.
3. We need to have a link to End User Terms of Use (see 4)
4. Attribution text needs tweaking (see 5 and 6)
5. Keep the login info locked away and not open (see 2)


Key bits:

1. "For the avoidance of doubt, the map image must not be hosted on a server or provided as a download"

2. "You must register a Login. You shall not select or use a Login with the intent of impersonating another person or entity and shall keep Your Login confidential and shall not allow any other person to use such Login to access any part of the OpenSpace API, Ordnance Survey Data or our website"

3. "You may create Derived Data, and You may permit End Users to create Derived Data, in connection with Your Application. In the event that You or any End User creates Derived Data, such Derived Data shall be owned by Us, save that if any Derived Data is created which is a severable improvement (as defined by Commission Regulation (EC) No 772/2004, known as the Technology Transfer Block Exemption) of the Ordnance Survey Data then such Derived Data shall be owned by the person or entity creating the same"

4. "a copy of the End User Terms of Use is made easily accessible to End Users through the hypertext link, ‘Terms of Use’, within theApplication;"

5. "The appropriate acknowledgement is:
‘© Crown copyright and database rights [year] Ordnance Survey’ for large window screens; and
‘© Crown copyright 2013’ for small window screens of 320 pixels or less in width."

6. "You must ensure that the OS OpenSpace logo to include ‘powered by OpenSpace’ is included in a conspicuous position in Your Application and You must not (nor may You permit others to) tamper with or remove such trade mark."

7. 'Unacceptable Financial Gain' means any payment, revenue, credit, or money’s worth received by, or accruing to, You (or an End User, or any third party connected to You or an End User) (directly or indirectly) for:
(i) allowing End Users to access and use Your Application;
(ii) displaying the Ordnance Survey Data (or Derived Data owned by Us) on Your Application, or any part of it; and/or
(iii) using, or allowing End Users or other third parties to view, download, use and otherwise exploit, any Ordnance Survey Data (or Derived Data owned by Us);

**Comment by peterkwells** [comment]
Also can @Floppy @pezholio @pikesley @JeniT remember to ask me at ODcamp tomorrow about "platform plays". I want to check that we all know something that's easier to explain in person with a picture. No concern but good to know.

**Comment by Floppy** [comment]
Oh, good god, the End User Terms of Use is a massive license contained within our license that we need to host on our site. FFS. This is why people ignore these things.

**Comment by Floppy** [comment]
@peterkwells can we insert the content of Schedule 2 of http://www.ordnancesurvey.co.uk/business-and-government/licensing/licences/os-openspace-developer-agreement.html into our site terms? Where should we put it?

**Comment by peterkwells** [comment]
1. +1 for simpler human-friendly licences
2. We probably need a "Terms and Conditions" link alongside the "Privacy Policy link" at the bottom. Can you create that and leave some holding text:

"Terms of use can be complicated things.

We'll have a simple one up soon.

In the meantime please be aware that our search page uses maps provided by the Ordnance Survey. Their terms and conditions can be found in Schedule 2 here <link>. Please respect them."

3. I'll work on the rest over the weekend

**Comment by Floppy** [comment]
Okey dokey.

**Comment by Floppy** [comment]
Done.

**Comment by peterkwells** [comment]
Ta. Let's leave this open to track me doing simple t's and c's.
