### ISSUE TITLE
Research CKAN plugin

### ISSUE THREAD

**Issue by pkqk** [theodi/shared#675]
* setup a CKAN install
* Look into how to make a basic CKAN plugin
* collate fields from standard CKAN setup and other plugins that could map the metadata to ODC answers
* expose internal data on an url endpoint so it can be discovered by ODC

Part of https://github.com/theodi/open-data-certificate/issues/1181

**Comment by pikesley** [comment]
http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html might be helpful.

I can help you with this @danielgavrilov

**Comment by pezholio** [comment]
@danielgavrilov - Also worth looking at this, which pulls datasets from ODCs to display a badge https://github.com/datagovuk/ckanext-certificates

**Comment by pezholio** [comment]
Also, this PR seems to be going some way towards doing what we want to do https://github.com/datagovuk/ckanext-certificates/pull/4/files

**Comment by danielgavrilov** [comment]
That PR seems to only send the URL of the dataset on create/update and let ODC do the guessing? It would probably be better if the plugin itself pre-populated some answers (?), but default CKAN fields are only: _title, description, tags, license, source, version, author, author name + email, maintainer name + email_

...which means most CKAN sites add their own custom fields, and these would be site specific making it hard to extract answers without any configuration.

- Should the plugin maybe **introduce new fields in the "new dataset" form**? This is harder to integrate on existing sites because it would break forms & duplicate fields, but it can be made optional. 
- Should there be a **configurable mapping**? As in, CKAN sites customise their forms themselves and provide some sort of mapping of fields in form => answers on ODC?
- Should we **leave the guessing responsibility to ODC**, which leaves sites simply notifying us when a dataset is created/updated (as in the PR) and us taking care of mapping the meta.

Let me know if I'm missing something because I probably am.

**Comment by pezholio** [comment]
Ah, yes. ODC does actually do the guessing for you - if the dataset comes from a CKAN repository, it uses [DataKitten](https://github.com/theodi/data_kitten) to take the metadata from the dataset and guess a whole bunch of fields. Try starting a certificate for a Data.gov.uk repository and you'll see what I mean. Most of the grunt work is done [here](https://github.com/theodi/open-data-certificate/blob/staging/app/models/kitten_data.rb)

**Comment by danielgavrilov** [comment]
Yeah James told me about it yesterday. Is it enough for the plugin to simply let us know when a dataset is created/updated or should it do more?

**Comment by danielgavrilov** [comment]
I created https://github.com/theodi/ckan-api-inspector to help with this—it lists every metadata field, what percentage of packages it appears in and the values it can have. It should make it easier to see all the data we can extract from specific CKAN sites.
