### ISSUE TITLE
Non-blocking validation in csvlint.rb

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#725]
Get csvlint.rb able to validate files in a non-blocking fashion so that the app can support streaming data. See #712.

**Comment by quadrophobiac** [comment]
`Validator` class currently executes in a 'blocking' fashion - no feedback or control is yielded to the user or process that calls the `Validator`
It would be more beneficial to provide `$stdout` feedback as the file is being validated
Refactor Validator to be a wrapper around a new StreamingValidation class to preserve existing interface and to ensure existing functionality is not broken
- [ ] refactor `def validate` into StreamingValidation class
- [ ] employ `if @limit_lines && current_line > @limit_lines` as a means of yielding control back to Validation Wrapper
- [ ]

**Comment by Floppy** [comment]
There are two possible methods for deciding when to yield: First is to give it all the data in one go and have it yield control back every few lines, the alternative is to have it validate everything it's given but only pass in a bit at a time. 

Either would work, but the latter might be more compatible with streaming upload/download later on. However, the first method will work fine to drive out the structure of what we want to do, so if that's simpler for now, go for it and we'll iterate.

**Comment by quadrophobiac** [comment]
Changes are made in the branch 
https://github.com/theodi/csvlint.rb/tree/feature-non-blocking-validation
to run a file in pseudo streaming fashion type this from CMD line
`bundle exec csvlint features/fixtures/$FILE.csv --limit-lines $N`

So in attempting to work out how to solve the Streaming feature request I have realised that I don’t really know anything about how to handle the control of execution  
As I understood it the desired outcome was to have a method which would return control to the Validator class as it processed N no of lines of a CSV file  
Instead all I managed to author so far was a while loop which will parse N amount of lines at a time, but because it’s a while loop there is no point at which the execution control exits the while loop (and whichever method it happens to be in)  

I’ve look at the various ways ruby has of controlling loops, and it seems like Procs or yield blocks might be useful, but I can’t figure out a way that they would work with the existing Validation Gem
It seems that refactoring the gem so that it doesn’t call it’s validate action within its own Validation.initialise method would help make the steps required a lot clearer. The class as it stood, and even more so with the changes I made, relies on lots of instance variables, some of which aren’t initialised in the main initialise function. This seems like a problem and it’d be really good to know what could be done instead of resorting to that

i wanted to test the functionality by the two new tests added
`“(it) should return true until there are no rows left to read”`
`“(it) should process a CSV file incrementally based on limit_lines"`
I couldn’t write the logic for these tests because I do not know how to pause execution of the streaming loop

**Comment by pezholio** [comment]
This is passing in its current state, but we have massive fail when pulling the the CSVW changes from master, because of the assumptions that were made about the order of things happening (mainly getting HTTP headers etc). I'm parking this for now.

**Comment by pezholio** [comment]
We now only have 6 failing tests (all CSVW related) Could do with @jenit's input on this https://travis-ci.org/theodi/csvlint.rb/jobs/83098785

**Comment by pezholio** [comment]
All this work is done and ready to merge! \o/ Going to wait until we've crafted a release for the CSVW stuff (and check that nothing breaks the web app) before merging however

**Comment by pezholio** [comment]
I might have to park this until someone with better git knowledge than me can clean up the history. Tried about 4 interactive rebases to clean up the commits, and something's gone wrong every time. I'd rather not merge until the commits were a bit tidier. Our fault for not giving proper Git training!

**Comment by pezholio** [comment]
Done and in master now. Just need to drop the release, which I'll do tomorrow!

**Comment by pezholio** [comment]
https://rubygems.org/gems/csvlint/versions/0.2.1 \o/
