### ISSUE TITLE
Update Eventbrite code

### ISSUE THREAD

**Issue by Floppy** [theodi/shared#798]

**Comment by pkqk** [comment]
I've made the eventbrite handling code work as much as possible based on the new api.

However based on the information that the v3 eventbrite api provides, we cannot work out how a ticket was paid for.

This means that the way we generate invoices and feed them into Xero will fail as soon as Eventbrite turn off the the old api (which was due to happen a year ago but is being delayed as an important Eventbrite client is being slow to update, so we'll get no warning when it does go away)

We are going to have to find a new way to decide what to write on an invoice and a way for finance to reconcile payments in paypal/xero etc.

/cc @Floppy

**Comment by Floppy** [comment]
Waiting on code deploy for #898 to bring things up to Ruby 2 before we fix this.

**Comment by Floppy** [comment]
Nope, we can carry on. Belay that.

**Comment by pezholio** [comment]
I think this is currently impossible. It's in the roadmap apparently, but not ETA. I've asked on the developers group for any workarounds, but I'm going to park this for now until we hear from them either way. If it's a negative, we can try and figure out a solution

**Comment by pezholio** [comment]
This is good to go https://github.com/theodi/open-orgn-services/pull/509

**Comment by pezholio** [comment]
So, this is merged in, but we can't pull it into services manager until we upgrade it to Ruby 2, which we can do when @pikesley gets back
